# Generated by Django 4.0.6 on 2022-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
