# Generated by Django 4.0.6 on 2022-07-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_landingpage_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='referred_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
