# Generated by Django 4.0.6 on 2022-07-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_landingpage_referred_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='home.landingpage'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='home.landingpage'),
        ),
    ]
