# Generated by Django 4.0.6 on 2022-07-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_referral_author_alter_referral_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.landingpage'),
        ),
    ]
