# Generated by Django 4.0.6 on 2022-07-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_points_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.landingpage'),
        ),
    ]
