# Generated by Django 4.0.6 on 2022-08-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='interest_sec',
        ),
        migrations.AddField(
            model_name='property',
            name='stage',
            field=models.CharField(default='Interest', max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='interest_sec',
            field=models.BooleanField(default=False),
        ),
    ]
