# Generated by Django 4.0.6 on 2022-08-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_property_interest_sec_property_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedprop',
            name='contract_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownedprop',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ownedprop',
            name='funded_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownedprop',
            name='interest_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownedprop',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
