# Generated by Django 4.0.6 on 2022-08-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_ownedprop_contract_stage_ownedprop_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedprop',
            name='contract_stage',
        ),
        migrations.RemoveField(
            model_name='ownedprop',
            name='interest_stage',
        ),
    ]
